import type { ProfileTitleDef } from "../catalog";

export const META_TITLES: ProfileTitleDef[] = [
  {
    id: "six-game-regular",
    label: "Six-Game Regular",
    rarity: "rare",
    category: "meta",
    unlockRule: "gamesPlayed",
    unlockParams: { min: 6 },
  },
  {
    id: "first-on-board",
    label: "First on the Board",
    rarity: "common",
    category: "meta",
    unlockRule: "diversity",
    unlockParams: { gamesWithScores: 1 },
  },
  {
    id: "arcade-architect",
    label: "Arcade Architect",
    rarity: "legendary",
    category: "meta",
    unlockRule: "diversity",
    unlockParams: { gamesWithScores: 5 },
  },
  {
    id: "combo-hunter",
    label: "Combo Hunter",
    rarity: "rare",
    category: "meta",
    unlockRule: "stat",
    unlockParams: { stat: "maxCombo", min: 25 },
  },
  {
    id: "flow-survivor",
    label: "Flow Survivor",
    rarity: "rare",
    category: "meta",
    unlockRule: "stat",
    unlockParams: { stat: "zenParticipation", min: 1 },
  },
  {
    id: "zen-tourist",
    label: "Zen Tourist",
    rarity: "rare",
    category: "meta",
    unlockRule: "zenAllGames",
    unlockParams: { min: 6 },
  },
  {
    id: "streak-keeper",
    label: "Streak Keeper",
    rarity: "rare",
    category: "meta",
    unlockRule: "streak",
    unlockParams: { days: 7 },
  },
  {
    id: "badge-collector",
    label: "Badge Collector",
    rarity: "legendary",
    category: "meta",
    unlockRule: "achievementCount",
    unlockParams: { min: 30 },
  },
  {
    id: "legendary-viber",
    label: "Legendary Viber",
    rarity: "legendary",
    category: "meta",
    unlockRule: "tier",
    unlockParams: { tier: "Legend" },
  },
  {
    id: "passport-certified",
    label: "Passport Certified",
    rarity: "rare",
    category: "meta",
    unlockRule: "passport",
  },
];
